### ISSUE TITLE
Neo4j query

### ISSUE THREAD

**Issue by zhangjoe99** [stakwork/sphinx-nav#110]
Neo4j Cypher query

**Input**
Two lists
_Topic_list_: []
_Weight_list_: []

Example:
_Topic_list_: ['taro', 'utxo']
_Weight_list_: [4, 3]
(Weight 4 is associated with 'taro' and 3 is associated with 'utxo')

**Output**
Content nodes from neo4j

**Details**
Neo4j contains topic nodes connected to content nodes with (weighted) relationships between them.
The relationship type between the two nodes can be either type "HUMAN" or type "ML", both of which have a weight value associated. (two nodes can be connected by both types or only one)
Goal is to return content nodes connected to topic nodes with a topic in _Topic_list_. Take the sum of the weights of the relationships between them (Example: HUMAN weight 1 + ML weight 0.2 = 1.2) and multiply that value by the corresponding value in _Weight_list_

To get started:
"""
with ['taro', 'utxo'] as topic_list, [4, 3] as weight_list
MATCH (t:Topic)-[r]-(c:Content)
WHERE t.topic IN topic_list
RETURN c, r.weight as weight ORDER BY weight DESC LIMIT 10
"""

This query does not take into account the _Weight_list_ nor the fact that there can be two relationships **r** (HUMAN and ML) between Topic and Content nodes (if there are, add their weights)

Edit:
If content is connected to multiple topics in topic_list. Will need to add all the resulting weights.
Example:
If content is connected to topic1 and topic2 by edge1 and edge2 respectively. Take the weight of edge1 and multiply by the corresponding value in weight_list, and add that to the (weight of edge2 multiplied by the value in weight_list)

**Comment by Raj725** [comment]
@zhangjoe99 are the weights for HUMAN & ML relationships fixed? or do we need to read from the relationship property?

**Comment by zhangjoe99** [comment]
> @zhangjoe99 are the weights for HUMAN & ML relationships fixed? or do we need to read from the relationship property?

The weights should be read from the relationship property with name "weight"
As in the example above, with r.weight

**Comment by Raj725** [comment]
@zhangjoe99 Thanks for the quick reply. I deleted my comment when I noticed it.

**Comment by zhangjoe99** [comment]
@Raj725 

Ahh good question. Yes, the weight in that case would have to be added.
So if content is connected to topic1 and topic2 by edge1 and edge2 respectively. Take the weight of edge1 and multiply by the corresponding value in weight_list, and add that to the (weight of edge2 multiplied by the value in weight_list)

**Comment by Raj725** [comment]
@zhangjoe99 Please try this Cypher if it's working. 
I do not have the data to verify the result:

```
WITH ['taro', 'utxo'] as topic_list, [4, 3] as weight_list
WITH [i IN RANGE(0, size(topic_list) - 1) | {topic: topic_list[i], weight: weight_list[i]}] AS pairs
UNWIND pairs AS pair 
MATCH (t:Topic)-[r]-(c:Content)
WHERE t.topic = pair.topic
WITH c, pair.weight as weight, sum(r.weight) as rel_weights
RETURN c, sum(weight*rel_weights) as total_weight 
ORDER BY total_weight 
DESC LIMIT 10
```

**Comment by zhangjoe99** [comment]
@Raj725 Wow that seems to be working!
