### ISSUE TITLE
edge distance based on weight

### ISSUE THREAD

**Issue by soup20** [stakwork/sphinx-nav#69]
We want to vary the distance between nodes based on the weight of the edge. If an edge has a higher weight, the two nodes should be closer together. If an edge has a lower weight, the nodes should be farther apart. However we should remember to keep the minimum edge distance in place to avoid big clumps of nodes.

**Comment by plell** [comment]
link distance is now based on type, i think this makes more sense because relevance doesnt come across well as a distance between nodes when there is so much happening. a color may be better feedback. what do you think?
