### ISSUE TITLE
add loading message

### ISSUE THREAD

**Issue by soup20** [stakwork/sphinx-nav#94]
Let's add a progress bar to display while a search is loading.

We want the user to understand what we're loading and get an approximate idea of how long they'll be waiting. A good way to do this would be:
- a bar that gradually fills in until the search results are ready
- messages saying things like: "Searching podcast index", "Searching YouTube", "Searching Twitter Spaces", "Finding transcripts", "Loading audio clips", "Loading video clips"

**Comment by plell** [comment]
this one is done~ https://github.com/stakwork/sphinx-nav/pull/95
